[package]
name = "first_word_slice_param"
version = "0.1.0"
authors = ["Maksim Khortov <xoptov@mail.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
